/* ═══════════════════════════════════════════════════════════════
   MemeMeter Engine — mememeter.js
   Result arrays, category weights, audio prefixes
   ═══════════════════════════════════════════════════════════════ */

Platform.registerEngine({
    name: 'MemeMeter',
    slug: 'mememeter',
    description: 'Aaj Tum Kya Nikloge?',
    audioBasePath: '../audio/',

    /* ── Category Weights ───────────────────────────────────── */
    categories: {
        ALPHA: { weight: 30, label: 'Alpha Frequency' },
        SAVAGE: { weight: 30, label: 'Dominance Protocol' },
        SILENT: { weight: 15, label: 'Silent Operator' },
        CLOWN: { weight: 20, label: 'Reality Check' },
        STABLE: { weight: 5, label: 'Balanced Core' }
    },

    /* ── Audio Prefixes (auto-detected: prefix_01.mp3, prefix_02.mp3, …) */
    audioPrefixes: {
        ALPHA: 'alpha',
        SAVAGE: 'savage',
        SILENT: 'silent',
        CLOWN: 'clown',
        STABLE: 'stable'
    },

    /* ── Loading Messages ───────────────────────────────────── */
    loadingMessages: [
        "System tumhari history scan kar raha hai…",
        "Confidence level analyze ho raha hai…",
        "Energy frequency match ho rahi hai…",
        "Purane screenshots investigate ho rahe hain…",
        "Rizz level calculate ho raha hai…",
        "Tumhare aura ka spectrum decode ho raha hai…",
        "Brain cells count karte karte thak gaye…",
        "Astrological + Wi-Fi analysis on…",
        "Tumhare reels watch history check ho rahi hai…",
        "Final identity report compile ho raha hai…"
    ],

    /* ── 141 Results ────────────────────────────────────────── */
    results: [

        // ══ ALPHA (30) — Calm Dominance, Silent Strength ════════
        { category: "ALPHA", emoji: "👑", title: "Sigma Throne", text: "Log shor karte hain. Tum impact banate ho. Farak yehi hai." },
        { category: "ALPHA", emoji: "🐺", title: "Lone Wolf Protocol", text: "Akele chalte ho. Par raasta tumhare peeche crowd bana deta hai." },
        { category: "ALPHA", emoji: "🗿", title: "Stone Face Ruler", text: "Tumhara silence itna loud hai, log apni galtiyan khud samajh jaate hain." },
        { category: "ALPHA", emoji: "🦅", title: "Eagle Altitude", text: "Neeche ka shor tumhe sunai nahi deta. Kyunki tum udaan pe ho." },
        { category: "ALPHA", emoji: "🧊", title: "Zero Kelvin", text: "Tumhare paas reaction nahi hota. Sirf decision hota hai." },
        { category: "ALPHA", emoji: "🎯", title: "Locked In", text: "Jab sab distractions chase karte hain, tum results collect karte ho." },
        { category: "ALPHA", emoji: "🖤", title: "Dark Authority", text: "Kisi se permission nahi lete. Kisi ko explanation nahi dete." },
        { category: "ALPHA", emoji: "🌑", title: "Shadow Command", text: "Tumhe dekhne ki zaroorat nahi. Tumhara asar mehsoos hota hai." },
        { category: "ALPHA", emoji: "💀", title: "Deadpan Dominance", text: "Tumhara poker face hi tumhara sabse powerful weapon hai." },
        { category: "ALPHA", emoji: "🔥", title: "Controlled Burn", text: "Andar toofan hai. Bahar sirf strategy hai." },
        { category: "ALPHA", emoji: "⚡", title: "Silent Voltage", text: "Current low hai par jab girta hai toh system reset ho jaata hai." },
        { category: "ALPHA", emoji: "🧠", title: "Architect Mind", text: "Log react karte hain. Tum 3 moves pehle se plan kar chuke hote ho." },
        { category: "ALPHA", emoji: "🏴", title: "Flagless Empire", text: "Koi title nahi. Koi label nahi. Bas authority hai." },
        { category: "ALPHA", emoji: "🛡️", title: "Unbreakable Frame", text: "Pressure tumhe todta nahi. Pressure tumse seekhta hai." },
        { category: "ALPHA", emoji: "⛓️", title: "Unchained", text: "Logon ki opinions tumhare liye background noise hai. Nothing more." },
        { category: "ALPHA", emoji: "🎧", title: "World On Mute", text: "Headphones laga ke duniya mute ki. Tab se peace hai." },
        { category: "ALPHA", emoji: "🧬", title: "Rare Blueprint", text: "Tumhari copy banana chahein toh bhi ingredients available nahi hain." },
        { category: "ALPHA", emoji: "🌊", title: "Depth Over Noise", text: "Surface pe shaant. Andar samundar hai. Woh bhi khamosh waala." },
        { category: "ALPHA", emoji: "🕶️", title: "Invisible Power", text: "Tum kamre mein ho ya nahi — energy shift hota hai." },
        { category: "ALPHA", emoji: "💎", title: "Pressure Made", text: "Jitna pressure padta hai, utne refined hote jaate ho." },
        { category: "ALPHA", emoji: "🐆", title: "Patient Predator", text: "Tum wait nahi karte. Tum observe karte ho. Phir execute." },
        { category: "ALPHA", emoji: "🏔️", title: "Summit Mind", text: "Tumhara perspective itna upar se hai, baaki logon ko map chahiye." },
        { category: "ALPHA", emoji: "🔒", title: "Locked Vault", text: "Jo tumhare andar hai woh kisi ke paas nahi. Aur kabhi hoga bhi nahi." },
        { category: "ALPHA", emoji: "🪨", title: "Granite Will", text: "Log opinions badalte hain mausam ke saath. Tum nahi." },
        { category: "ALPHA", emoji: "⏳", title: "Timeless Standard", text: "Trends aate hain, jaate hain. Tumhara level constant hai." },
        { category: "ALPHA", emoji: "🌙", title: "Midnight Monarch", text: "Raat ko jab duniya soti hai, tumhara empire build hota hai." },
        { category: "ALPHA", emoji: "🦁", title: "Silent Roar", text: "Dahaadne ki zaroorat nahi. Tumhari presence hi kaafi hai." },
        { category: "ALPHA", emoji: "🔱", title: "Trident Authority", text: "Teen cheezon pe control — mind, time, aur narrative." },
        { category: "ALPHA", emoji: "🧲", title: "Gravity Field", text: "Tum attract nahi karte. Log khud tumhari orbit mein aa jaate hain." },
        { category: "ALPHA", emoji: "🎯", title: "Permanent Focus", text: "Distractions tumhare paas aati hain. Aur waapas chali jaati hain." },

        // ══ SAVAGE (30) — Intimidating Confidence ════════════════
        { category: "SAVAGE", emoji: "🔥", title: "Atmosphere Shifter", text: "Tum kamre mein aate ho. Energy badalti hai. Bina kuch bole." },
        { category: "SAVAGE", emoji: "💣", title: "Truth Bomb", text: "Sach bolte ho itni cleanly, log samajh nahi paate ki roast hua ya advice mili." },
        { category: "SAVAGE", emoji: "🐍", title: "Venom Precision", text: "Zuban se zahar nahi nikalta. Surgery hoti hai. Clean cuts." },
        { category: "SAVAGE", emoji: "⚔️", title: "War Mode", text: "Tum ladaai mein nahi jaate. Ladaai tumhare paas aati hai. Aur haar ke jaati hai." },
        { category: "SAVAGE", emoji: "🧨", title: "Controlled Explosion", text: "Calm rehte ho. Par jab react karte ho, landscape change ho jaata hai." },
        { category: "SAVAGE", emoji: "🪓", title: "Clean Cut Artist", text: "Bakwaas sunne ka time nahi. Ek line mein khatam. Done." },
        { category: "SAVAGE", emoji: "🏴‍☠️", title: "No Rules Zone", text: "Rules tumhare liye banaye nahi gaye. Tum apne rules khud likhte ho." },
        { category: "SAVAGE", emoji: "💅", title: "Unbothered Royalty", text: "Chase nahi karte. Replace karte ho. Aur upgrade pe upgrade." },
        { category: "SAVAGE", emoji: "🦈", title: "Apex Predator", text: "Tumhe competition nahi milta. Log compete karne se pehle hi hat jaate hain." },
        { category: "SAVAGE", emoji: "🌶️", title: "Extra Spice", text: "Tumhari presence itni intense hai, normal log uncomfortable ho jaate hain." },
        { category: "SAVAGE", emoji: "🎤", title: "Final Word", text: "Discussion tum khatam karte ho. Koi uske baad nahi bolta." },
        { category: "SAVAGE", emoji: "🪦", title: "Legacy Builder", text: "Log yaad karenge. Par tab tak tum aage badh chuke hoge." },
        { category: "SAVAGE", emoji: "🦁", title: "Territorial King", text: "Tumhara territory tumhara mindset hai. Aur woh unbreakable hai." },
        { category: "SAVAGE", emoji: "🧯", title: "Fire Starter & Stopper", text: "Aag lagaate bhi ho. Bujhaate bhi ho. Dono pe full control." },
        { category: "SAVAGE", emoji: "🗡️", title: "Surgical Strike", text: "Words aise use karte ho jaise scalpel. Precise. No extra damage." },
        { category: "SAVAGE", emoji: "📵", title: "Selectively Available", text: "Har kisi ke liye available nahi. Privilege hai tumse baat karna." },
        { category: "SAVAGE", emoji: "⚡", title: "High Voltage Aura", text: "Tumhari energy handle karna har kisi ke bas ki baat nahi." },
        { category: "SAVAGE", emoji: "🏹", title: "One Shot. One Kill.", text: "Ek chance milta hai. Ek hi chahiye. Kaam ho jaata hai." },
        { category: "SAVAGE", emoji: "🥶", title: "Cold Authority", text: "Gussa nahi aata. Silence aati hai. Aur woh zyada khatarnak hai." },
        { category: "SAVAGE", emoji: "🎯", title: "Zero Misses", text: "Jab bhi baat karte ho, nishana lagta hai. Har baar. Bina try kiye." },
        { category: "SAVAGE", emoji: "🔱", title: "Triple Impact", text: "Ek line mein teen chezein todh dete ho — ego, argument, aur confidence." },
        { category: "SAVAGE", emoji: "🐆", title: "Silent Strike", text: "Dikhte nahi. Sunai nahi dete. Par jab aate ho, sab feel karte hain." },
        { category: "SAVAGE", emoji: "💎", title: "Pressure Proof", text: "Jitna dabaaoge, utna chamkoge. Yehi tumhara chemistry hai." },
        { category: "SAVAGE", emoji: "🌪️", title: "Controlled Chaos", text: "Bahar se storm lagte ho. Par andar har move calculated hai." },
        { category: "SAVAGE", emoji: "🖤", title: "Dark Elegance", text: "Rudeness nahi hai. Standards hain. Aur woh bahut oonche hain." },
        { category: "SAVAGE", emoji: "👁️", title: "X-Ray Vision", text: "Ek nazar mein log samajh aate hain. Unhe pata bhi nahi chalta." },
        { category: "SAVAGE", emoji: "🧊", title: "Frost Protocol", text: "Jitna ignore karte ho, utna zyada log tumhari taraf aate hain." },
        { category: "SAVAGE", emoji: "🪙", title: "Rare Currency", text: "Tumhara time itna valuable hai, log appointment le ke baat karte hain." },
        { category: "SAVAGE", emoji: "🔥", title: "Scorched Earth", text: "Jab jaate ho, kuch nahi bachta. Sirf tumhara impact rehta hai." },
        { category: "SAVAGE", emoji: "⚔️", title: "Gladiator Mind", text: "Arena mein akele khade ho. Aur phir bhi favourite ho." },

        // ══ SILENT (30) — Underrated Mastermind ══════════════════
        { category: "SILENT", emoji: "🗿", title: "Silent Observer", text: "Jab sab react karte hain. Tum calculate karte ho." },
        { category: "SILENT", emoji: "🧍", title: "Still Water Runs Deep", text: "Surface pe kuch nahi. Par neeche poora game chal raha hai." },
        { category: "SILENT", emoji: "🎮", title: "Background Boss", text: "Main character nahi ho. Par story tumhare bina chale bhi nahi." },
        { category: "SILENT", emoji: "🧠", title: "Data Collector", text: "Baat kam karte ho. Par sab kuch yaad rakhte ho. Sab kuch." },
        { category: "SILENT", emoji: "🌫️", title: "Fog Mode", text: "Log tumhe samajhne ki koshish karte hain. Fog aur dense ho jaata hai." },
        { category: "SILENT", emoji: "📡", title: "Silent Antenna", text: "Sab kuch receive karte ho. Broadcast kuch nahi. Strategic silence." },
        { category: "SILENT", emoji: "🔭", title: "Long Game Player", text: "Log aaj ke liye khelte hain. Tum 5 saal baad ke liye." },
        { category: "SILENT", emoji: "🧊", title: "Frozen Strategy", text: "Tumhari patience hi tumhara sabse khatarnak weapon hai." },
        { category: "SILENT", emoji: "🦉", title: "Night Owl Thinker", text: "Raat ko jab sab sote hain, tumhara dimaag empire build karta hai." },
        { category: "SILENT", emoji: "🪵", title: "Rooted Presence", text: "Log hilte hain opinions se. Tum wahin khade rehte ho. Unbothered." },
        { category: "SILENT", emoji: "📦", title: "Boxed Genius", text: "Simple dikhte ho. Par andar itna depth hai, samundar bhi insecure ho jaaye." },
        { category: "SILENT", emoji: "🔒", title: "Vault Personality", text: "Tumhare secrets itne safe hain, tumne khud ko bhi nahi bataye." },
        { category: "SILENT", emoji: "🧭", title: "Internal Compass", text: "Sab trend follow karte hain. Tum apna direction khud set karte ho." },
        { category: "SILENT", emoji: "🪑", title: "Throne In Disguise", text: "Chair lagte ho. Par jab uthte ho sab ko realize hota hai — support tum the." },
        { category: "SILENT", emoji: "🌑", title: "Dark Horse", text: "Koi tumhe race mein count nahi karta. Yehi tumhara advantage hai." },
        { category: "SILENT", emoji: "📋", title: "Mental Notepad", text: "Likha kuch nahi. Par har conversation ka record dimaag mein hai." },
        { category: "SILENT", emoji: "🐢", title: "Tortoise Protocol", text: "Dheere chalte ho. Par finish line pe pehle hote ho. Hamesha." },
        { category: "SILENT", emoji: "🤖", title: "Emotion Firewall", text: "React nahi karte. Process karte ho. Phir precision se respond karte ho." },
        { category: "SILENT", emoji: "🚶", title: "Walkaway Power", text: "Chup chaap chale jaate ho. Aur yehi log ko sabse zyada disturb karta hai." },
        { category: "SILENT", emoji: "🫥", title: "Invisible Architect", text: "Log tumhe notice nahi karte. Par unki life tumhari wajah se chal rahi hai." },
        { category: "SILENT", emoji: "🎭", title: "Mask Master", text: "Koi nahi jaanta tum kya soch rahe ho. Yeh design hai, flaw nahi." },
        { category: "SILENT", emoji: "🔔", title: "Silent Alarm", text: "Jab tum bolte ho, log sun-te hain. Kyunki tum roz nahi bolte." },
        { category: "SILENT", emoji: "🧩", title: "Missing Context", text: "Log tumhe incomplete samajhte hain. Puzzle complete karna unke bas ka nahi." },
        { category: "SILENT", emoji: "🛒", title: "Patience Investor", text: "Jab sab panic karte hain, tum calmly wait karte ho. Returns tumhare paas aate hain." },
        { category: "SILENT", emoji: "🧾", title: "Receipt Keeper", text: "Tumne kuch bola nahi. Par jab bologe, saboot ke saath bologe." },
        { category: "SILENT", emoji: "🕳️", title: "Black Hole Mind", text: "Sab kuch absorb karte ho. Bahar kuch nahi aata. Strategy is loading." },
        { category: "SILENT", emoji: "🌿", title: "Still Forest", text: "Bahar se shaant jungle. Andar ek poora ecosystem chal raha hai." },
        { category: "SILENT", emoji: "🔇", title: "Muted But Aware", text: "Mic off hai. Par chat mein sab padh rahe ho. Silently judging." },
        { category: "SILENT", emoji: "🧪", title: "Lab Mode", text: "Log experiments karte hain life mein. Tum pehle results study karte ho." },
        { category: "SILENT", emoji: "🎯", title: "Delayed Impact", text: "Tumhara aaj ka silence kal ka sabse powerful move banega." },

        // ══ CLOWN (30) — Sharp Roast, Playful Humiliation ════════
        { category: "CLOWN", emoji: "🤡", title: "Full HD Clown", text: "Confidence tumhara Full HD hai. Bas content thoda 144p ka hai." },
        { category: "CLOWN", emoji: "🎪", title: "Circus CEO", text: "Circus nahi join kiya. Circus khol liya. Aur khud hi star act ho." },
        { category: "CLOWN", emoji: "🤣", title: "Roast Magnet", text: "Log tumse nahi haste. Log tum pe haste hain. Aur tum proud ho." },
        { category: "CLOWN", emoji: "🎈", title: "Inflated Ego Airlines", text: "Ego se bhare ho. Talent ki seat pe bhi ego baitha hai." },
        { category: "CLOWN", emoji: "🍕", title: "Leftover Personality", text: "Log tumhe tab yaad karte hain jab koi aur available nahi hota." },
        { category: "CLOWN", emoji: "😜", title: "Walking Red Flag", text: "Itne red flags hain tumhare paas, bullfight mein invite aaya hai." },
        { category: "CLOWN", emoji: "🦆", title: "Quack Genius", text: "IQ test diya. Test ne resignation de diya." },
        { category: "CLOWN", emoji: "🧃", title: "Expired Juice", text: "Energy toh hai. Bas expiry date 2019 mein nikal gayi." },
        { category: "CLOWN", emoji: "🎭", title: "Double Shift Clown", text: "Ek face se hasaate ho. Doosre face se confuse karte ho. Dono mein expert." },
        { category: "CLOWN", emoji: "🪃", title: "Boomerang Disaster", text: "Galtiyan karte ho. Seekhte nahi. Repeat karte ho. Pro max." },
        { category: "CLOWN", emoji: "🐒", title: "Monkey Brain Pro", text: "Dimaag mein 50 tabs khule hain. Sab mein buffering. Koi kaam ka nahi." },
        { category: "CLOWN", emoji: "🌭", title: "Uninvited Legend", text: "Bulaya nahi tha. Aaye. Scene bhi le liya. Credit bhi le liya." },
        { category: "CLOWN", emoji: "🎉", title: "Accidental Main Character", text: "Plot tumhare bina chalti. Par tum aaye aur genre comedy ho gayi." },
        { category: "CLOWN", emoji: "🫠", title: "Melting Confidence", text: "Confidence aise pighal raha hai jaise ice cream garam plate pe." },
        { category: "CLOWN", emoji: "🦥", title: "Sloth Sigma", text: "Sigma ban-ne ki koshish ki. Alarm snooze kiya. Wapas so gaye." },
        { category: "CLOWN", emoji: "🧲", title: "L Magnet", text: "W ke paas se guzarte ho. Par L tumhare inbox mein already hai." },
        { category: "CLOWN", emoji: "🎶", title: "Out of Tune Star", text: "Gaana gaaye bina hi log earphones dhundh lete hain. Talent." },
        { category: "CLOWN", emoji: "🪤", title: "Self-Sabotage Pro", text: "Success ke bilkul paas the. Phir khud pe trip kiya. Classic." },
        { category: "CLOWN", emoji: "🍿", title: "Drama DLC", text: "Tumhare bina drama incomplete hai. Tum paid DLC ho drama ke." },
        { category: "CLOWN", emoji: "🧸", title: "Cute But Clueless", text: "Itne cute ho ki koi seriously nahi leta. Aur tum confused ho kyun." },
        { category: "CLOWN", emoji: "🤪", title: "Random Access Personality", text: "Tumhari next move predict karna weather forecast se bhi mushkil hai." },
        { category: "CLOWN", emoji: "🪞", title: "Mirror Shock", text: "Aina bhi dekhke bolta hai — 'aaj nahi bhai.'" },
        { category: "CLOWN", emoji: "📱", title: "Screenshot Risk", text: "Itni bakwaas karte ho ki log chats save karte hain evidence ke liye." },
        { category: "CLOWN", emoji: "🎓", title: "PhD in Excuses", text: "Kaam karne mein zero interest. Reason dene mein PhD hai." },
        { category: "CLOWN", emoji: "🛸", title: "Alien Logic", text: "Tumhari thinking itni different hai, NASA bhi confuse hai." },
        { category: "CLOWN", emoji: "🔋", title: "1% Battery Life", text: "Hamesha low energy pe ho. Par bakwaas ke liye turbo mode on hai." },
        { category: "CLOWN", emoji: "🧭", title: "Lost GPS", text: "Direction sense hai hi nahi. Par confidence se galat raste pe chal rahe ho." },
        { category: "CLOWN", emoji: "📉", title: "Stonks Expert", text: "Har decision ke baad graph neeche jaata hai. Financial advisor mat ban-na." },
        { category: "CLOWN", emoji: "🎪", title: "Main Event Clown", text: "Tum joke nahi sunaate. Tum khud punchline ho." },
        { category: "CLOWN", emoji: "🐸", title: "Frog Syndrome", text: "Kuye mein baithke ocean ki baat karte ho. Cute effort though." },

        // ══ STABLE (21) — Unchanged ══════════════════════════════
        { category: "STABLE", emoji: "🌿", title: "Stable Soul", text: "Tum woh calm dost ho jisko sab 2 AM pe call karte hain." },
        { category: "STABLE", emoji: "☕", title: "Chai & Chill", text: "90% problems chai aur patience se solve kar lete ho." },
        { category: "STABLE", emoji: "🐢", title: "Turtle Power", text: "Slow and steady. Ghar bhi peeth pe leke chalte ho." },
        { category: "STABLE", emoji: "📚", title: "Library Vibes", text: "Shaant, organized, aur silently sabko judge karte ho." },
        { category: "STABLE", emoji: "🌻", title: "Sunflower Human", text: "Chaos mein bhi roshni ki taraf dekhte ho." },
        { category: "STABLE", emoji: "🛌", title: "Sleep Schedule King", text: "Jab sab 3 AM pe hustle karte hain, tum wisely recharge hote ho." },
        { category: "STABLE", emoji: "🧘", title: "Inner Peace Unlocked", text: "Itna chill level achieve kiya hai, monks bhi likhte hain tumpe." },
        { category: "STABLE", emoji: "🍵", title: "Matcha Energy", text: "Trendy, calm, thoda kadwa, par sab chahte hain tumhe." },
        { category: "STABLE", emoji: "🏡", title: "Homebody Hero", text: "Tumhara sabse bada adventure TV remote dhundhna hai." },
        { category: "STABLE", emoji: "🎋", title: "Bamboo Bender", text: "Jhuk jaate ho par toot-te kabhi nahi. Flexible legend." },
        { category: "STABLE", emoji: "🌤️", title: "Partly Cloudy", text: "Na hamesha dhoop, na hamesha baarish. Bas vibe ho rahi hai." },
        { category: "STABLE", emoji: "🧸", title: "Comfort Zone King", text: "Comfort zone se kyun niklo jab usme snacks hain?" },
        { category: "STABLE", emoji: "📖", title: "Open Book", text: "Honest, predictable, aur chapter 5 pe surprisingly deep." },
        { category: "STABLE", emoji: "🌙", title: "Moonlight Mode", text: "Jab koi nahi dekh raha, tab sabse zyada chamakte ho." },
        { category: "STABLE", emoji: "🪴", title: "Plant Parent Energy", text: "Plants, log, pizza dough — sab ko paalte ho." },
        { category: "STABLE", emoji: "🔋", title: "Fully Charged", text: "Jab sab fumes pe hain, tumhari battery hamesha green hai." },
        { category: "STABLE", emoji: "🧩", title: "Missing Piece", text: "Har friend group ko tumhari zaroorat hai. Puzzle complete karte ho." },
        { category: "STABLE", emoji: "🛟", title: "Lifebuoy Friend", text: "Khud float karte ho aur doosron ko bhi karaate ho. Kindness ka ocean." },
        { category: "STABLE", emoji: "🎻", title: "Smooth Operator", text: "Tumhari life mein lo-fi soundtrack aur warm blanket hai." },
        { category: "STABLE", emoji: "📬", title: "Reliable Mailbox", text: "Hamesha deliver karte ho. Dhoop ho ya baarish. No tracking needed." },
        { category: "STABLE", emoji: "🧺", title: "Laundry Day Peace", text: "Apni life neatly fold karte ho jab doosre air dry kar rahe hain." }
    ]
});
